---
name: Build & Deploy Nix Artifacts
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/**'
  page_build:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""
          upstream-cache: https://lehmanator.cachix.org
          use-flakehub: false
          use-gha-cache: true
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          send-statistics: false
  build:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""
          upstream-cache: https://lehmanator.cachix.org
          use-flakehub: false
          use-gha-cache: true
      - id: build-html
        name: Build flake packages.default
        run: nix build
      - run: 'mkdir -p ./out && cp ./result/*.html ./out'
      - id: build-pdf
        name: Build PDF
        run: 'nix run .#pdf -- ./out/resume.pdf'
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './out'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
