name: Build & Deploy Nix Artifacts
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  build:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: Build flake outputs
        run: nix build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload resume artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./result"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
