name: Build & Deploy Nix Artifacts
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          # Disable telemetry
          diagnostic-endpoint: ""
          #nix_path: nixpkgs=channel:nixos-unstable
      - name: Use binary cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          # Disable telemetry
          diagnostic-endpoint: ""
          # Use my binary cache (uses cache.nixos.org upstream)
          upstream-cache: https://lehmanator.cachix.org
          #flakehub-api-server: https://api.flakehub.com
          #flakehub-cache-server: https://cache.flakehub.com
          #flakehub-flake-name: jsonresume-nix
          #listen: "127.0.0.1:37515"
          use-flakehub: false
          use-gha-cache: true
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          # Disable telemetry
          send-statistics: false
      - name: Build flake outputs
        run: nix build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload resume HTML artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./result/index.html"
      - name: Upload resume assets artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./result/photo.png"
      - name: Upload resume PDF artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./result/resume.pdf"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
