name: Check flake outputs
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #- name: Install Nix
      #  uses: cachix/install-nix-action@v22
      #  with:
      #    nix_path: nixpkgs=channel:nixos-unstable
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: "" # Disable telemetry
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Use binary cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: "" # Disable telemetry
          upstream-cache: https://lehmanator.cachix.org # Use my binary cache (which uses cache.nixos.org upstream)
      - name: Check flake outputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          send-statistics: false # Disable telemetry
      #- name: Check flake
      #  run: nix flake check
