---
name: Check flake outputs
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""
          upstream-cache: https://lehmanator.cachix.org
          use-flakehub: false
          use-gha-cache: true
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          send-statistics: false

      # Check formatting
      - name: Check nix file formatting
        run: 'nix fmt . -- --check'
      - name: Check yaml file formatting
        run: 'nix run nixpkgs#yamllint -- --format github .github/'
        # run: 'nix run nixpkgs#yamllint -- --strict --format github .github/'
      # - name: Check deadnix file formatting
      #   run: 'nix run nixpkgs#deadnix -- --fail .'
      - name: Check flake
        run: nix flake check
